version: "3.8"

services:
  image2text:
    container_name: image2text
    build:
      context: ./image2text
      dockerfile: Dockerfile
    command: python img_server.py
    volumes:
      - ./image2text:/app
      - ~/frontend/public/media:/data
    ports:
      - 8090:8080

  text2voice:
    container_name: text2voice
    build:
      context: ./text2voice
      dockerfile: docker/Dockerfile
    command: python server.py
    volumes:
      - ./text2voice:/app
    ports:
      - 8086:8080
