# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos.img2seq_pb2 as img2seq__pb2


class ImageCaptioningStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImageCaption = channel.unary_unary(
                '/pb.ImageCaptioning/ImageCaption',
                request_serializer=img2seq__pb2.Image.SerializeToString,
                response_deserializer=img2seq__pb2.Text.FromString,
                )


class ImageCaptioningServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ImageCaption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageCaptioningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ImageCaption': grpc.unary_unary_rpc_method_handler(
                    servicer.ImageCaption,
                    request_deserializer=img2seq__pb2.Image.FromString,
                    response_serializer=img2seq__pb2.Text.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.ImageCaptioning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageCaptioning(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ImageCaption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.ImageCaptioning/ImageCaption',
            img2seq__pb2.Image.SerializeToString,
            img2seq__pb2.Text.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
