model:
  _target_: img_server.ImageCaptionModel
  # Тип модели. "stub", "blip" или "llava"
  model_type: "blip"
  use_only_cuda: False
  use_translator: True
  translator: "google"

server:
  port: 8080
  ip: 0.0.0.0