version: 1
disable_existing_loggers: true
formatters:
  stdout_formatter:
    format: "%(asctime)s\t%(levelname)s\t%(name)s\t%(message)s"
handlers:
  stream_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: stdout_formatter
loggers:
  IMAGE2TEXT_MODEL_SERVER:
    level: DEBUG
    handlers: [stream_handler]
    propagate: False
root:
  level: DEBUG
  handlers: [stream_handler]